/*
 * QR Emergencias WS
 * API Rest QR Emergencias
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.qre.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import android.os.Parcelable;
import android.os.Parcel;

/**
 * ApiFieldError
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-10T21:22:21.097-03:00")
public class ApiFieldError implements Parcelable {
  @SerializedName("field")
  private String field = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("rejectedValue")
  private Object rejectedValue = null;

  public ApiFieldError field(String field) {
    this.field = field;
    return this;
  }

   /**
   * Get field
   * @return field
  **/
  public String getField() {
    return field;
  }

  public void setField(String field) {
    this.field = field;
  }

  public ApiFieldError message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public ApiFieldError rejectedValue(Object rejectedValue) {
    this.rejectedValue = rejectedValue;
    return this;
  }

   /**
   * Get rejectedValue
   * @return rejectedValue
  **/
  public Object getRejectedValue() {
    return rejectedValue;
  }

  public void setRejectedValue(Object rejectedValue) {
    this.rejectedValue = rejectedValue;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiFieldError apiFieldError = (ApiFieldError) o;
    return Objects.equals(this.field, apiFieldError.field) &&
        Objects.equals(this.message, apiFieldError.message) &&
        Objects.equals(this.rejectedValue, apiFieldError.rejectedValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(field, message, rejectedValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiFieldError {\n");
    
    sb.append("    field: ").append(toIndentedString(field)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    rejectedValue: ").append(toIndentedString(rejectedValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
  public void writeToParcel(Parcel out, int flags) {
     
    out.writeValue(field);

    out.writeValue(message);

    out.writeValue(rejectedValue);
  }

  public ApiFieldError() {
    super();
  }

  ApiFieldError(Parcel in) {
    
    field = (String)in.readValue(null);
    message = (String)in.readValue(null);
    rejectedValue = (Object)in.readValue(null);
  }
  
  public int describeContents() {
    return 0;
  }

  public static final Creator<ApiFieldError> CREATOR = new Creator<ApiFieldError>() {
    public ApiFieldError createFromParcel(Parcel in) {
      return new ApiFieldError(in);
    }
    public ApiFieldError[] newArray(int size) {
      return new ApiFieldError[size];
    }
  };
}

