/*
 * QR Emergencias WS
 * API Rest QR Emergencias
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.qre.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import android.os.Parcelable;
import android.os.Parcel;

/**
 * FileDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-10T21:22:21.097-03:00")
public class FileDTO implements Parcelable {
  @SerializedName("extension")
  private String extension = null;

  @SerializedName("mimeType")
  private String mimeType = null;

  @SerializedName("url")
  private String url = null;

  public FileDTO extension(String extension) {
    this.extension = extension;
    return this;
  }

   /**
   * Get extension
   * @return extension
  **/

  public String getExtension() {
    return extension;
  }

  public void setExtension(String extension) {
    this.extension = extension;
  }

  public FileDTO mimeType(String mimeType) {
    this.mimeType = mimeType;
    return this;
  }

   /**
   * Get mimeType
   * @return mimeType
  **/

  public String getMimeType() {
    return mimeType;
  }

  public void setMimeType(String mimeType) {
    this.mimeType = mimeType;
  }

  public FileDTO url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/

  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileDTO fileDTO = (FileDTO) o;
    return Objects.equals(this.extension, fileDTO.extension) &&
        Objects.equals(this.mimeType, fileDTO.mimeType) &&
        Objects.equals(this.url, fileDTO.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(extension, mimeType, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileDTO {\n");
    
    sb.append("    extension: ").append(toIndentedString(extension)).append("\n");
    sb.append("    mimeType: ").append(toIndentedString(mimeType)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
  public void writeToParcel(Parcel out, int flags) {
     
    out.writeValue(extension);

    out.writeValue(mimeType);

    out.writeValue(url);
  }

  public FileDTO() {
    super();
  }

  FileDTO(Parcel in) {
    
    extension = (String)in.readValue(null);
    mimeType = (String)in.readValue(null);
    url = (String)in.readValue(null);
  }
  
  public int describeContents() {
    return 0;
  }

  public static final Creator<FileDTO> CREATOR = new Creator<FileDTO>() {
    public FileDTO createFromParcel(Parcel in) {
      return new FileDTO(in);
    }
    public FileDTO[] newArray(int size) {
      return new FileDTO[size];
    }
  };
}

