/*
 * QR Emergencias WS
 * API Rest QR Emergencias
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.qre.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;


import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
import android.os.Parcelable;
import android.os.Parcel;

/**
 * HospitalizationDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-10T21:22:21.097-03:00")
public class HospitalizationDTO implements Parcelable {
  @SerializedName("date")
  private OffsetDateTime date = null;

  @SerializedName("institution")
  private String institution = null;

  @SerializedName("reason")
  private String reason = null;

  /**
   * Gets or Sets type
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    /*
    SURGERY("SURGERY"),
    
    ADMISSION("ADMISSION"),
    */

    cirugia("cirugia"),
    admision("admision"),

    ;

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return TypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("type")
  private TypeEnum type = null;

  public HospitalizationDTO date(OffsetDateTime date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/

  public OffsetDateTime getDate() {
    return date;
  }

  public void setDate(OffsetDateTime date) {
    this.date = date;
  }

  public HospitalizationDTO institution(String institution) {
    this.institution = institution;
    return this;
  }

   /**
   * Get institution
   * @return institution
  **/

  public String getInstitution() {
    return institution;
  }

  public void setInstitution(String institution) {
    this.institution = institution;
  }

  public HospitalizationDTO reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/

  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public HospitalizationDTO type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/

  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HospitalizationDTO hospitalizationDTO = (HospitalizationDTO) o;
    return Objects.equals(this.date, hospitalizationDTO.date) &&
        Objects.equals(this.institution, hospitalizationDTO.institution) &&
        Objects.equals(this.reason, hospitalizationDTO.reason) &&
        Objects.equals(this.type, hospitalizationDTO.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, institution, reason, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HospitalizationDTO {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    institution: ").append(toIndentedString(institution)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
  public void writeToParcel(Parcel out, int flags) {
     
    out.writeValue(date);

    out.writeValue(institution);

    out.writeValue(reason);

    out.writeValue(type);
  }

  public HospitalizationDTO() {
    super();
  }

  HospitalizationDTO(Parcel in) {
    
    date = (OffsetDateTime)in.readValue(OffsetDateTime.class.getClassLoader());
    institution = (String)in.readValue(null);
    reason = (String)in.readValue(null);
    type = (TypeEnum)in.readValue(null);
  }
  
  public int describeContents() {
    return 0;
  }

  public static final Creator<HospitalizationDTO> CREATOR = new Creator<HospitalizationDTO>() {
    public HospitalizationDTO createFromParcel(Parcel in) {
      return new HospitalizationDTO(in);
    }
    public HospitalizationDTO[] newArray(int size) {
      return new HospitalizationDTO[size];
    }
  };
}

