/*
 * QR Emergencias WS
 * API Rest QR Emergencias
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.qre.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;


import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import android.os.Parcelable;
import android.os.Parcel;

/**
 * LoginUserDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-10T21:22:21.097-03:00")
public class LoginUserDTO implements Parcelable {
  @SerializedName("lastName")
  private String lastName = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("roles")
  private List<String> roles = null;

  public LoginUserDTO lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/

  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public LoginUserDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public LoginUserDTO roles(List<String> roles) {
    this.roles = roles;
    return this;
  }

  public LoginUserDTO addRolesItem(String rolesItem) {
    if (this.roles == null) {
      this.roles = new ArrayList<String>();
    }
    this.roles.add(rolesItem);
    return this;
  }

   /**
   * Get roles
   * @return roles
  **/

  public List<String> getRoles() {
    return roles;
  }

  public void setRoles(List<String> roles) {
    this.roles = roles;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginUserDTO loginUserDTO = (LoginUserDTO) o;
    return Objects.equals(this.lastName, loginUserDTO.lastName) &&
        Objects.equals(this.name, loginUserDTO.name) &&
        Objects.equals(this.roles, loginUserDTO.roles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastName, name, roles);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginUserDTO {\n");
    
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
  public void writeToParcel(Parcel out, int flags) {
     
    out.writeValue(lastName);

    out.writeValue(name);

    out.writeValue(roles);
  }

  public LoginUserDTO() {
    super();
  }

  LoginUserDTO(Parcel in) {
    
    lastName = (String)in.readValue(null);
    name = (String)in.readValue(null);
    roles = (List<String>)in.readValue(null);
  }
  
  public int describeContents() {
    return 0;
  }

  public static final Creator<LoginUserDTO> CREATOR = new Creator<LoginUserDTO>() {
    public LoginUserDTO createFromParcel(Parcel in) {
      return new LoginUserDTO(in);
    }
    public LoginUserDTO[] newArray(int size) {
      return new LoginUserDTO[size];
    }
  };
}

