/*
 * QR Emergencias WS
 * API Rest QR Emergencias
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.qre.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.qre.models.MedicalRecordDTO;
import com.qre.models.Sort;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import android.os.Parcelable;
import android.os.Parcel;

/**
 * PageOfMedicalRecordDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-10T21:22:21.097-03:00")
public class PageOfMedicalRecordDTO implements Parcelable {
  @SerializedName("content")
  private List<MedicalRecordDTO> content = null;

  @SerializedName("first")
  private Boolean first = null;

  @SerializedName("last")
  private Boolean last = null;

  @SerializedName("number")
  private Integer number = null;

  @SerializedName("numberOfElements")
  private Integer numberOfElements = null;

  @SerializedName("size")
  private Integer size = null;

  @SerializedName("sort")
  private Sort sort = null;

  @SerializedName("totalElements")
  private Long totalElements = null;

  @SerializedName("totalPages")
  private Integer totalPages = null;

  public PageOfMedicalRecordDTO content(List<MedicalRecordDTO> content) {
    this.content = content;
    return this;
  }

  public PageOfMedicalRecordDTO addContentItem(MedicalRecordDTO contentItem) {
    if (this.content == null) {
      this.content = new ArrayList<MedicalRecordDTO>();
    }
    this.content.add(contentItem);
    return this;
  }

   /**
   * Get content
   * @return content
  **/

  public List<MedicalRecordDTO> getContent() {
    return content;
  }

  public void setContent(List<MedicalRecordDTO> content) {
    this.content = content;
  }

  public PageOfMedicalRecordDTO first(Boolean first) {
    this.first = first;
    return this;
  }

   /**
   * Get first
   * @return first
  **/

  public Boolean getFirst() {
    return first;
  }

  public void setFirst(Boolean first) {
    this.first = first;
  }

  public PageOfMedicalRecordDTO last(Boolean last) {
    this.last = last;
    return this;
  }

   /**
   * Get last
   * @return last
  **/

  public Boolean getLast() {
    return last;
  }

  public void setLast(Boolean last) {
    this.last = last;
  }

  public PageOfMedicalRecordDTO number(Integer number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/

  public Integer getNumber() {
    return number;
  }

  public void setNumber(Integer number) {
    this.number = number;
  }

  public PageOfMedicalRecordDTO numberOfElements(Integer numberOfElements) {
    this.numberOfElements = numberOfElements;
    return this;
  }

   /**
   * Get numberOfElements
   * @return numberOfElements
  **/

  public Integer getNumberOfElements() {
    return numberOfElements;
  }

  public void setNumberOfElements(Integer numberOfElements) {
    this.numberOfElements = numberOfElements;
  }

  public PageOfMedicalRecordDTO size(Integer size) {
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/

  public Integer getSize() {
    return size;
  }

  public void setSize(Integer size) {
    this.size = size;
  }

  public PageOfMedicalRecordDTO sort(Sort sort) {
    this.sort = sort;
    return this;
  }

   /**
   * Get sort
   * @return sort
  **/

  public Sort getSort() {
    return sort;
  }

  public void setSort(Sort sort) {
    this.sort = sort;
  }

  public PageOfMedicalRecordDTO totalElements(Long totalElements) {
    this.totalElements = totalElements;
    return this;
  }

   /**
   * Get totalElements
   * @return totalElements
  **/

  public Long getTotalElements() {
    return totalElements;
  }

  public void setTotalElements(Long totalElements) {
    this.totalElements = totalElements;
  }

  public PageOfMedicalRecordDTO totalPages(Integer totalPages) {
    this.totalPages = totalPages;
    return this;
  }

   /**
   * Get totalPages
   * @return totalPages
  **/

  public Integer getTotalPages() {
    return totalPages;
  }

  public void setTotalPages(Integer totalPages) {
    this.totalPages = totalPages;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PageOfMedicalRecordDTO pageOfMedicalRecordDTO = (PageOfMedicalRecordDTO) o;
    return Objects.equals(this.content, pageOfMedicalRecordDTO.content) &&
        Objects.equals(this.first, pageOfMedicalRecordDTO.first) &&
        Objects.equals(this.last, pageOfMedicalRecordDTO.last) &&
        Objects.equals(this.number, pageOfMedicalRecordDTO.number) &&
        Objects.equals(this.numberOfElements, pageOfMedicalRecordDTO.numberOfElements) &&
        Objects.equals(this.size, pageOfMedicalRecordDTO.size) &&
        Objects.equals(this.sort, pageOfMedicalRecordDTO.sort) &&
        Objects.equals(this.totalElements, pageOfMedicalRecordDTO.totalElements) &&
        Objects.equals(this.totalPages, pageOfMedicalRecordDTO.totalPages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(content, first, last, number, numberOfElements, size, sort, totalElements, totalPages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PageOfMedicalRecordDTO {\n");
    
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    first: ").append(toIndentedString(first)).append("\n");
    sb.append("    last: ").append(toIndentedString(last)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    numberOfElements: ").append(toIndentedString(numberOfElements)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("    totalElements: ").append(toIndentedString(totalElements)).append("\n");
    sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
  public void writeToParcel(Parcel out, int flags) {
     
    out.writeValue(content);

    out.writeValue(first);

    out.writeValue(last);

    out.writeValue(number);

    out.writeValue(numberOfElements);

    out.writeValue(size);

    out.writeValue(sort);

    out.writeValue(totalElements);

    out.writeValue(totalPages);
  }

  public PageOfMedicalRecordDTO() {
    super();
  }

  PageOfMedicalRecordDTO(Parcel in) {
    
    content = (List<MedicalRecordDTO>)in.readValue(MedicalRecordDTO.class.getClassLoader());
    first = (Boolean)in.readValue(null);
    last = (Boolean)in.readValue(null);
    number = (Integer)in.readValue(null);
    numberOfElements = (Integer)in.readValue(null);
    size = (Integer)in.readValue(null);
    sort = (Sort)in.readValue(Sort.class.getClassLoader());
    totalElements = (Long)in.readValue(null);
    totalPages = (Integer)in.readValue(null);
  }
  
  public int describeContents() {
    return 0;
  }

  public static final Creator<PageOfMedicalRecordDTO> CREATOR = new Creator<PageOfMedicalRecordDTO>() {
    public PageOfMedicalRecordDTO createFromParcel(Parcel in) {
      return new PageOfMedicalRecordDTO(in);
    }
    public PageOfMedicalRecordDTO[] newArray(int size) {
      return new PageOfMedicalRecordDTO[size];
    }
  };
}

